= Listing Node Services
:description: pass:q[The services running on a specific node can be listed, with their respective port numbers, by means of the `GET /pools/default/nodeServices` method and URI.]
:page-topic-type: reference

[abstract]
{description}

[#http-method-and-uri]
== HTTP methods and URI

----
GET /pools/default/nodeServices
----

[#rest-listing-node-services-description]
== Description

Couchbase Services (Data, Query, Index, Search, Analytics, Eventing, and Backup) and other essential processes are associated with specific port numbers.
A complete list of the associations is provided in xref:install:install-ports.adoc[Couchbase Server Ports].

The services and processes currently occupying these port numbers on a given node are listed by means of the `GET /pools/default/nodeServices` method and URI.

[#curl-syntax]
== Curl Syntax

----
curl -v -X GET -u [admin]:[password]
http://[ip-address]:8091/pools/default/nodeServices
----

[#responses]
== Responses

Success gives the status `200 OK`, and returns an object containing a list that includes all services and their port numbers, plus any alternate addresses and port numbers that may have been configured.

If an incorrect primary address is specified, a `Could not resolve host: <host-number>` error message is displayed.

If the URI is incorrectly specified, a `404 Object Not Found` error is flagged.

[#example]
== Example

The following example pipes the returned object to the `jq` command, to facilitate readability:

----
curl -v -X GET -u Administrator:password \
http://10.143.192.101:8091/pools/default/nodeServices | jq
----

The displayed output is as follows:

----
{
  "rev": 35119,
  "nodesExt": [
    {
      "services": {
        "backupAPI": 8097,
        "backupAPIHTTPS": 18097,
        "backupGRPC": 9124,
        "capi": 8092,
        "capiSSL": 18092,
        "cbas": 8095,
        "cbasSSL": 18095,
        "eventingAdminPort": 8096,
        "eventingDebug": 9140,
        "eventingSSL": 18096,
        "fts": 8094,
        "ftsGRPC": 9130,
        "ftsGRPCSSL": 19130,
        "ftsSSL": 18094,
        "indexAdmin": 9100,
        "indexHttp": 9102,
        "indexHttps": 19102,
        "indexScan": 9101,
        "indexStreamCatchup": 9104,
        "indexStreamInit": 9103,
        "indexStreamMaint": 9105,
        "kv": 11210,
        "kvSSL": 11207,
        "mgmt": 8091,
        "mgmtSSL": 18091,
        "n1ql": 8093,
        "n1qlSSL": 18093,
        "projector": 9999
      },
      "thisNode": true
    }
  ],
  "revEpoch": 1,
  "clusterCapabilitiesVer": [
    1,
    0
  ],
  "clusterCapabilities": {
    "n1ql": [
      "costBasedOptimizer",
      "indexAdvisor",
      "javaScriptFunctions",
      "inlineFunctions",
      "enhancedPreparedStatements",
      "readFromReplica"
    ],
    "search": [
      "vectorSearch",
      "scopedSearchIndex"
    ]
  }
}
----

The output may include information on ports used by:

* REST and HTTP-based management, including Couchbase Web Console (`8091` and `18091`).

* The Eventing Service (`8096`, `9140`, and `18096`).

* The Index Service (`9100`, `9101`, `9102`, `9103`, `9104`, `9105`, `19102`, and `9999`).

* The Data Service (`11210` and `11207`).

* XDCR and Views (`8092` and `18092`).

* The Query Service (`8093` and `18093`).

* The Backup Service (`8097`, `18097`, and `9124`).

[#see-also]
== See Also

A complete list of Couchbase Services and the ports they occupy, along with information on custom port mapping, is provided in xref:install:install-ports.adoc[Couchbase Server Ports].
